### PR TITLE
Add SPAREIRQ_* IRQs

### PR DESCRIPTION
**Pull request by pta2002**
Add spare IRQs to the SVD patch.

I named them SPAREIRQ_IRQ_* instead of SW*_IRQ like in the RP2040 PAC, since in this case they are explicitly named in the datasheet.

(Addresses #4)

### CODE REVIEW

**Comment by 9names** [comment]
I don't know if we should prefer the name in the rp2350 datasheet over our existing name (in this instance).
RP never bothered to name them for rp2040, and honestly the names they have chosen are clearly auto-generated based on what was sensible during hardware design and aren't as nice for humans.

If we do decide to name them as this PR suggests, I think we should rename them in rp2040-pac for consistency.
Thoughts @jannic @thejpster?

**Comment by thejpster** [comment]
I think there's more benefit to rp2350-pac matching rp2040-pac than there is to rp2350-pac matching an obscure part of the datasheet; and the names are pretty obvious anyway.

So I'd vote for changing this PR to use the same names as the rp2040-pac.

**Comment by pta2002** [comment]
If there's consensus on that I can change this PR to the same names as the rp2040 then. I do agree that if we were to keep a consistent name, it does not make sense to break the rp2040's compatibility

**Review by ithinuel — APPROVED** [review]

**Comment by 9names** [comment]
Thanks for the PR. This work is merged in #8 so closing this PR.

**Pull request closed without merging**
